Refer to https://www.tensors.net/p-tutorial-1

In [2]:
# T1.1: Diagrammatic notation


##### Lets initialize some tensors in Python/Numpy
import numpy as np
# tensor with randomly generated entries, order 3, dims: 2-by-3-by-4
A = np.random.rand(2,3,4)
print("Tensor A:", "\n", A, "\n")

# identity matrix, order 2, dims: 5-by-5 
B = np.eye(5,5)
print("Tensor B:", "\n", B, "\n")

# tensor of 1's, order 4, dims: 2-by-4-by-2-by-4 
# (there are 2 * 4 number of 2-by-4 tensors).
C = np.ones((2,4,2,4))
print("Tensor C:", "\n", C, "\n")

# matrix of 0's, order 2, dims: 3-by-5
D = np.zeros((3,5))
print("Tensor D:", "\n", D, "\n")

# initialize complex random tensor, dims: 2-by-3-by-4
E = np.random.rand(2,3,4) + 1j*np.random.rand(2,3,4)
print("Tensor E:", "\n", E, "\n")

Tensor A: 
 [[[0.57130068 0.89198214 0.49150695 0.98478355]
  [0.92368479 0.55787562 0.02685778 0.93946455]
  [0.34069544 0.93195297 0.02875961 0.10661732]]

 [[0.51758595 0.20477194 0.08042577 0.82024306]
  [0.73602519 0.75851708 0.59410255 0.30676689]
  [0.1678108  0.60909282 0.20218601 0.32610742]]] 

Tensor B: 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]] 

Tensor C: 
 [[[[1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]]]


 [[[1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]]]] 

Tensor D: 
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 

Tensor E: 
 [[[0.97294522+0.1288059j  0.30225609+0.68237038j 0.64733261+0.93411073j
   0.17151388+0.38549052j]
  [0.67912778+0.90340555j 0.11218973+0.62173287j 0.69360561+0.4683511j
   0.71968303+0.09911354j]
  [0.0

In [4]:
# T1.2: Permute and reshape operations


import numpy as np

##### Ex.1.2(a):Transpose
# A is a 4-by-4-by-4-by-4 tensor.
# So, it is a 4 * 4 number of 4-by-4 matrices.
A = np.random.rand(4,4,4,4)
Atilda = A.transpose(3,0,1,2)

print("Tensor A:", "\n", A, "\n")
print("Transpose of A:", "\n", Atilda, "\n")


##### Ex.1.2(b):Reshape
# Combine the second and third indices into a single index.
# dim of the new index = (dim of the second ind.) * (dim of the third ind.)
B = np.random.rand(4,4,4)
Btilda = B.reshape(4,4**2)

print("Tensor B:", "\n", B, "\n")
print("Reshaping B:", "\n", Btilda, "\n")


## Technical notes! ##
# 1. Python vs. MATLAB/Julia
# MATLAB/Julia use column-major order.
# Python uses row-major order.

# 2. Permutation incurs often non-negligible computational cost.
# Reshaping incurs negligible computational cost.

Tensor A: 
 [[[[0.95729942 0.04145077 0.54807066 0.96213095]
   [0.18687035 0.69001621 0.58125367 0.26830625]
   [0.5951994  0.88926079 0.9996506  0.41592814]
   [0.17512477 0.03615498 0.60205446 0.89736124]]

  [[0.87381472 0.38629709 0.67425445 0.69518672]
   [0.76259559 0.44546072 0.78425929 0.94138533]
   [0.18351646 0.64689275 0.69386363 0.08343689]
   [0.43800266 0.03992467 0.01969266 0.8649929 ]]

  [[0.64036007 0.318471   0.41196271 0.37585224]
   [0.73958143 0.71600033 0.55149024 0.86847646]
   [0.23719072 0.05757465 0.13123195 0.64588717]
   [0.13085735 0.75509245 0.53221301 0.75822603]]

  [[0.61045171 0.29077004 0.20621179 0.02483353]
   [0.0571828  0.27928343 0.50531678 0.06611952]
   [0.37674655 0.85239291 0.84826208 0.33341802]
   [0.46311289 0.9335941  0.36418006 0.59510092]]]


 [[[0.4836592  0.00122153 0.31835189 0.33402015]
   [0.32780768 0.51467594 0.29214651 0.36877455]
   [0.25640105 0.15402205 0.2648044  0.26438588]
   [0.72812445 0.7301944  0.28421662 0.66953258

In [12]:
# T1.3: Binary tensor contractions: a contraction between a pair of tensors


import numpy as np
import sys
np.set_printoptions(threshold=sys.maxsize)
##### Ex.1.3(a): Binary Tensor Contraction
d = 3  # decreased the value to make it easier to print
A = np.random.rand(d,d,d,d)
B = np.random.rand(d,d,d,d)

Ap  = A.transpose(0,2,1,3);  Bp = B.transpose(0,3,1,2)
App = Ap.reshape(d**2,d**2); Bpp = Bp.reshape(d**2,d**2)

# App @ Bpp is a binary tensor contarction here.
Cpp = App @ Bpp;             C   = Cpp.reshape(d,d,d,d)


## TODO: uncomment the following several lines for understanding the concept.

# print("Transpose A:", "\n", Ap, "\n")
# print("Reshaped transpose A:", "\n", App, "\n")

# print("Transpose B:", "\n", Bp, "\n")
# print("Reshaped transpose B:", "\n", Bpp, "\n")

# print("Binary tensor contraction of App and Bpp:", "\n", Cpp, "\n")
# print("Getting back to a 4-order tensor:", "\n", C, "\n")

In [ ]:
# T1.4: Contraction costs

import numpy as np
##### Ex.1.4(c): Tensor network evaluation
d = 10
A = np.random.rand(d,d) 
B = np.random.rand(d,d)
C = np.random.rand(d,d)

# (i) Evaluare network via summation over internal indices
# Complexity = d * d * d * d = d^4
F0 = np.zeros((d,d))
for di in range(d):
    for dj in range(d):
        for dk in range(d):
            for dl in range(d):
                F0[di,dj] = F0[di,dj] + A[di,dk]*B[dk,dl]*C[dl,dj]
            
# (ii) Evaluare network via sequence of binary contractions
# Complexity = d * d + d * d = 2 d^2
# Therefore, this process is more cost-effective than the above one.
F1 = (A @ B) @ C

print("Matrix A:", "\n", A, "\n")
print("Matrix B:", "\n", B, "\n")
print("Matrix C:", "\n", C, "\n")

print("Result F0", "\n", F0, "\n")
print("Result F1", "\n", F1, "\n")

# Even if these two processes output the same result,
# due to the different decimal precision in each computation,
# np.array_equal(F0, F1) returns False.
# But the results F0 and F1 are actually the same.
print("F0 == F1 is", np.allclose(F0, F1))

Matrix A: 
 [[0.26056042 0.7824571  0.5370072  0.21449272 0.73132949 0.1284832
  0.90575891 0.72225928 0.19078123 0.39549725]
 [0.3114169  0.05377026 0.60453705 0.53215996 0.31079781 0.22202693
  0.57570899 0.3989998  0.29101819 0.70292207]
 [0.20577928 0.30826195 0.50915534 0.89520487 0.89359388 0.88353284
  0.12369607 0.7732593  0.39965174 0.12532914]
 [0.96938947 0.21474494 0.05941035 0.22401013 0.20449527 0.22265134
  0.01208398 0.23520916 0.05084563 0.95314858]
 [0.61632665 0.12998768 0.98574437 0.98165828 0.01116323 0.88927796
  0.60381071 0.46286176 0.28934929 0.03873196]
 [0.99353177 0.10640866 0.4300052  0.02875542 0.63987354 0.13900626
  0.00825828 0.11731183 0.11274229 0.3242867 ]
 [0.5987459  0.34092486 0.47947564 0.40103251 0.04345954 0.17784765
  0.1787238  0.0496622  0.29453111 0.61709537]
 [0.88827351 0.91056533 0.94648825 0.25053512 0.83196398 0.42415682
  0.86329256 0.47282578 0.44400844 0.97483158]
 [0.79524468 0.76849427 0.22020385 0.59892048 0.69130542 0.59096559
 

# T1.4: Contraction costs

Remember that a contraction cost is calculates as follows:

<img src="pics/tutorial1_1.4b.png" alt="1.4b" width="400"/>

<br>

In this example,

<img src="pics/tutorial1_1.4d.png" alt="1.4d" width="600"/>

$$
\begin{align}
    \text{cost: } (A \times B) &=  |\text{dim} A| \cdot |\text{dim} B| / |\text{dim}{A \cap B}| \\ \notag
    &= (d^2 D) \cdot (d^2 D) / D \\ \notag
    &= d^4 D. \notag
\end{align}
$$

Let the contracted tensor of A and B is AB.

$$
\begin{align}
    \text{cost: } ((AB) \times C) &= |\text{dim} (AB)| \cdot |\text{dim} C| / |\text{dim} (AB) \cap C | \\ \notag
    &= d^4 \cdot (d^2 D) / d^2 \\ \notag
    &= d^4 D. \notag
\end{align}
$$


Then the total cost is
$$
\begin{align}
    \text{cost: } ((A \times C) \times B) &= \text{cost} (A \times B) + \text{cost} ((AB) \times C) \\ \notag
    &= d^4 D + d^4 D \\ \notag
    &= 2 d^4 D. \notag
\end{align}
$$

Therefore, computational costs may be different according to a contraction order.

A more straightforward method to compute the computational cost of a binary contraction is to multiply the dimensions of all the legs connected to the two tensors.
By multiplying the dimensions of the five legs (as indicated by the numbers), you can determine the cost of the $A \times B$ contraction.

<img src="pics/tutorial1_1.4d2.png" atl="1.4d2" width="400">

In [20]:
# T1.5: Contraction of tensor networks

# A reference to determining the optimal contraction sequence: https://doi.org/10.48550/arXiv.1304.6112

## ncon ##
# https://github.com/mhauru/ncon
# Internal index: first, second, third, ... = 1, 2, 3, ...
# External index: first, second, third, ... = -1, -2, -3, ...
# Index order: clockwise from 6 o'clock
# OutputTensor = ncon(TensorArray, IndexArray, ContOrder)


##### Ex.1.5(b): Contraction using ncon
import numpy as np
from ncon import ncon

d = 10
A = np.random.rand(d,d,d); B = np.random.rand(d,d,d,d)
C = np.random.rand(d,d,d); D = np.random.rand(d,d)

TensorArray = [A,B,C,D]
IndexArray = [[1,-2,2],[-1,1,3,4],[5,3,2],[4,5]]

# The following line does not work as count_order is not a proper keyword argument.
# E = ncon(TensorArray,IndexArray,cont_order = [5,3,4,1,2])

# Use the following one instead.
E = ncon(TensorArray,IndexArray,order = [5,3,4,1,2])

# You can omit the keyword argument 'order'.
# E = ncon(TensorArray,IndexArray)

# print(E)


##### Ex.1.5(c): Partial trace
d = 10
A = np.random.rand(d,d,d,d,d,d)

# Two indices labeled as 1 will be contracted.
# The result tensor is a d-by-d-by-d-by-d tensor.
B = ncon([A],[[-1,-2,1,-3,-4,1]])
print(B.shape)

##### Ex.1.5(d): Disjoint networks
d = 10
A = np.random.rand(d,d)
B = np.random.rand(d,d)

# Two disjoint networks A and B will be contracted to be C (d-by-d-by-d-by-d tensor)
C = ncon([A,B],[[-1,-2],[-3,-4]])
print(C.shape)

(10, 10, 10, 10)
(10, 10, 10, 10)


## Solutions to Problem Set 1:

### Pb.1(a)

Step 1. Start from the binary contraction of the minimum cost.

$\text{cost: } (A \times B) = d^6 \\$
$\text{cost: } (A \times C) = d^6 \\$
$\text{cost: } (B \times C) = d^7 \\$
$\text{cost: } (B \times E) = d^6 \\$
$\text{cost: } (C \times D) = d^6 \\$
$\text{cost: } (C \times E) = d^6 \\$
$\text{cost: } (E \times D) = d^5 \\$

So, the first choice is $(E \times D)$.

Step 2. After the first step, do a binary contraction of two tensors that has multiple legs between them.
If there are multiple legs between a pair of tensors, it causes a high computational cost in the rest of the process at a certain step.

After contracting tensors $D$ and $E$, $C$ and $DE$ will have two legs, so contract $C$ with $DE$. Cost: $d^6$.

Step 3. $CDE$ will have two legs with $B$. Cost: $d^6$.

Step 4. $A$ and $BCED$ will have two legs between them. Cost: $d^5$.

Answer: $((((D \times E) \times C ) \times B) \times A)$

Total cost: $2d^6 + 2d^5 = O(d^6)$

## Pb.1(b) - Solutions

<img src="pics/tutorial_1_pb1b.png" alt="pb1b" width="400">

Indices were labeled in a cirwise manner (clockwise from 6 o'clock), starting from $A$ ($[a1, a2, a3]$) then $C$ and $B$ (clockwisely A->B->C).

After a series of binary contraction, the contracted tensor will have three indices $[b_1, a_2, c_3]$.

```python
import numpy as np
from ncon import ncon
from timeit import default_timer as timer

d = 20
A = np.random.rand(d,d,d) 
B = np.random.rand(d,d,d)
C = np.random.rand(d,d,d)

##### Evaluate network via index summation
def tempfunct(A,B,C,d):
    D0 = np.zeros((d,d,d))
    # b1, a2, c3 are outer indices that will be three indices of the tensor D.
    for b1 in range(d):
        for a2 in range(d):
            for c3 in range(d):
            
                # a1, a3, c1 are internal indices that will be contracted.
                for a1 in range(d):
                    for a3 in range(d):
                        for c1 in range(d):
                            D0[b1,a2,c3] = D0[b1,a2,c3]+A[a1,a2,a3]*B[b1,a1,c1]*C[c1,a3,c3]
    return D0
```

```python
##### Evaluate network using reshape and permute
def tempfunct2(A,B,C,d):

    # Step 1. B[b1, a1, c1] and A[a1, a2, a3].
    # a1 will be contracted. So, transpose B.transpose(0,2,1) to make it Btilda[b1, c1, a1]
    # To contract Btilda[b1, c1, a1] with A[a1, a2, a3], indices except a1 will be reshaped as
    # [(b1 c1), a1] @ [a1, (a2 a3)] (contracted legs should be centered at).
    # Then convert the result to 4-order tensor (4 legs).
    Xmid = (B.transpose(0,2,1).reshape(d**2,d) @ A.reshape(d,d**2)).reshape(d,d,d,d)
    
    # Xmid has four legs: [b1, c1, a2, a3].
    # Because Xmid is connected to C by c1 and a3, c1 and a3 will be contracted.
    # Xmid[b1, c1, a2, a3] -> Xmidtilda[b1, a2, c1, a3] -> [(b1 a2), c1, a3] (by reshape).
    # C[c1, a3, c3] -> [(c1, a3), c3] (no transpose. Just reshape).
    # Then convert the result to 3-order tensor (4 legs).
    D1 = (Xmid.transpose(0,2,1,3).reshape(d**2,d**2) @ C.reshape(d**2,d)).reshape(d,d,d)
    return D1

##### Evaluate using ncon
# 'order' rather than 'count_order'
t0 = timer(); D2 = ncon([A,B,C],[[1,-2,2],[-1,1,3],[3,2,-3]], order = [1,2,3])
t_ncon = timer() - t0
```

<img src="pics/tutorial_1_pb1b2.png" alt="pb1b" width="400">

```python
##### Compare
t0 = timer(); D0 = tempfunct(A,B,C,d);
t_sum = timer() - t0

t0 = timer(); D1 = tempfunct2(A,B,C,d);
t_res = timer() - t0

tdiffs = [max(abs(D0-D1).flatten()),max(abs(D1-D2).flatten()),max(abs(D2-D0).flatten())]
ttimes = [t_sum, t_res, t_ncon]

print(tdiffs)
print(ttimes)

>>>[9.777068044058979e-12, 9.094947017729282e-13, 9.549694368615746e-12]
>>>[53.53751239995472, 0.0015054999385029078, 0.0017189999343827367]
```

In [26]:
##### Pb.1(b) - Solutions
import numpy as np
from ncon import ncon

d = 20
A = np.random.rand(d,d,d) 
B = np.random.rand(d,d,d)
C = np.random.rand(d,d,d)

##### Evaluate network via index summation
def tempfunct(A,B,C,d):
    D0 = np.zeros((d,d,d))
    for b1 in range(d):
        for a2 in range(d):
            for c3 in range(d):
                for a1 in range(d):
                    for a3 in range(d):
                        for c1 in range(d):
                            D0[b1,a2,c3] = D0[b1,a2,c3]+A[a1,a2,a3]*B[b1,a1,c1]*C[c1,a3,c3]
    return D0

from timeit import default_timer as timer
t0 = timer(); D0 = tempfunct(A,B,C,d);
t_sum = timer() - t0

##### Evaluate network using reshape and permute
def tempfunct2(A,B,C,d):
    Xmid = (B.transpose(0,2,1).reshape(d**2,d) @ A.reshape(d,d**2)).reshape(d,d,d,d)
    D1 = (Xmid.transpose(0,2,1,3).reshape(d**2,d**2) @ C.reshape(d**2,d)).reshape(d,d,d)
    return D1

t0 = timer(); D1 = tempfunct2(A,B,C,d);
t_res = timer() - t0

##### Evaluate using ncon
t0 = timer(); D2 = ncon([A,B,C],[[1,-2,2],[-1,1,3],[3,2,-3]], order = [1,2,3])
t_ncon = timer() - t0

##### Compare
tdiffs = [max(abs(D0-D1).flatten()),max(abs(D1-D2).flatten()),max(abs(D2-D0).flatten())]
ttimes = [t_sum, t_res, t_ncon]

In [27]:
print(tdiffs)
print(ttimes)

[9.777068044058979e-12, 9.094947017729282e-13, 9.549694368615746e-12]
[53.53751239995472, 0.0015054999385029078, 0.0017189999343827367]
